In [3]:
import numpy as np

Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


List Vs numpy Array

In [6]:
py_list = [1,2,3,4,5]
print(py_list *2)

np_array = np.array([1,2,3,4,5])
print(np_array *2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [10]:
import time

start = time.time()
py_list = [i*2 for  i in range(1000000)]
print("\n Time taken for list: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) *2
print("\n Time taken for numpy array: ", time.time() - start)




 Time taken for list:  0.09596037864685059

 Time taken for numpy array:  0.0055119991302490234


Creating array from scratch

In [5]:
from msilib import sequence


zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)

full = np.full((3,4),10)
print(full)

random = np.random.rand(3,4)
print(random)

sequence = np.arange(10, 10, 0.1)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0.67802919 0.50724436 0.40533503 0.15033515]
 [0.7626044  0.23908466 0.26343506 0.44051881]
 [0.64523811 0.44980708 0.51689429 0.90854062]]
[]


Vector, Matrix and Tensor

In [7]:
vector = np.array([1,2,3,4,5])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]],
                   [[13,14,15],[16,17,18]]])

print("Tensor: ", tensor)

Vector:  [1 2 3 4 5]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


Array Properties

In [9]:
arr =np.array([1,2,3,4,5])
print("Array: ", arr)

print("Shape: ", arr.shape)
print("Size:", arr.size)
print("Dimension: ", arr.ndim)
print("Data Type: ", arr.dtype)
print("Itemsize: ", arr.itemsize)
print("Total Size: ", arr.nbytes)



Array:  [1 2 3 4 5]
Shape:  (5,)
Size: 5
Dimension:  1
Data Type:  int64
Itemsize:  8
Total Size:  40


In [16]:
arr = np.arange(12)
print("Array Arange: ", arr)


Array Arange:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
Reshaped = arr.reshape((3,4))
print("Reshaped: ", Reshaped)

Reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
Flattened = Reshaped.flatten()
print("Flattened: ", Flattened)


Flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
# ravel(reurns view , insted of copy)
Raveled = Reshaped.ravel()
print("Raveled: ", Raveled)


Raveled:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
Transposed = Reshaped.T
print("Transposed: ", Transposed)

Transposed:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
